### ISSUE TITLE
suggestion: phase out `-state <string>` in favor of optional `-statefile <path>` or read from stdin if not provided

### ISSUE THREAD

**Issue by rhenning** [mdb/terraputs#6]
hey mike,

i'd like to suggest some alternate means of getting statefile json into `terraputs`. passing the state json as a string in `argv[]` works but can be somewhat unwieldy. statefiles can be large, often contain secrets, and things that the shell is likely to interpret as metacharacters, even in double-quoted strings.

In actual practice, i've run into two gotchas so far:

* CI/CD system ends up unwrapping the inner quotes during expansion of its `sh("terraputs -state '${statejson}' ...")` step and the json string ends up unquoted during exection and expanded by the shell, potentially causing errors like `Argument list too long`. Workarounds include all manner of multi-escaping, escaping backslashes with more backslashes in the shell command, etc.
* For large tfstates, even if properly quoted to avoid expansion, the statefile contents may actually be too long for the CI/CD system to effectively manage it as a command line argument.

The workflow I'm suggesting could effectively work around both those issues. In pseudocode:

```
infile := open(opts[statefile]) || file.stdin
process(infile)
```

I believe this would elegantly handle all of the following example workflows and sidestep the argument handling issues.

```
$ terraform show -json | terraputs -header ...
$ terraform state pull ; terraputs < terraform.tfstate
$ terraform show -json > tfstate.out ; terraputs -statefile tfstate.out
```

let me know what you think. i'm happy to pick it up but wanted to get it out of my head.

**Comment by mdb** [comment]
Thanks @rhenning ! I like your suggestions!

**Comment by mdb** [comment]
I'm going to close this issue, as `-state`, `-state-file`, and reading from stdin are all now supported. Thanks @rhenning !
